### ISSUE TITLE
Pre-release v2.0.0 is marked as latest in npm

### ISSUE THREAD

**Issue by yannickcr** [jscs-dev/babel-jscs#16]
The pre-release version `v2.0.0`is marked as the latest stable version in npm.

This leads to problems when installing/updating `jscs` and `babel-jscs`:

``` sh
$ npm install jscs babel-jscs -g # will install jscs 1.13.1 and babel-jscs 2.0.0, two incompatible versions
```

**Comment by hzoo** [comment]
Oh sorry, I didn't understand `npm publish` correctly - yeah it only works on jscs master branch or commit https://github.com/jscs-dev/node-jscs/commit/4d70439ab4a7f336725318624d7d5d2ff0201a7b. I also thought jscs would have a release soon so it wouldn't be an issue

**Comment by hzoo** [comment]
Going to close for now - I'm recommending everyone just uses `jscs . --esnext` (will use babel-jscs in the background) when the next jscs release comes out (or on current master).
