### ISSUE TITLE
Add JSCS tests

### ISSUE THREAD

**Issue by hzoo** [jscs-dev/babel-jscs#2]

**Comment by hzoo** [comment]
Can probably do something similar to https://github.com/babel/babel-eslint/pull/116

Will will need to modify jscs as well to support this? ESLint has a tester repo and had to be modified to allow the parser to be changed globally (since we want to run all tests with the `babel-jscs` parser).

**Comment by mrjoelkemp** [comment]
Can't [rewire](https://www.npmjs.com/package/rewire) esprima to be babel-jscs? It's a bit of a hack, but wouldn't require changing the core.

**Comment by hzoo** [comment]
Ok yeah I guess similar to all the module hacks for estraverse. We also could probably replace the estraverse module with just the babel visitor instead for jscs in tree-iterator

**Comment by hzoo** [comment]
Added as a submodule already\* in https://github.com/hzoo/babel-jscs/commit/cafdea63e0187d17c4cc0c77d6d359667784d373
