### ISSUE TITLE
requireSpacesInFunctionExpression breaks object literal methods

### ISSUE THREAD

**Issue by jussi-kalliokoski** [jscs-dev/babel-jscs#21]
Hi, thanks for this tool! :heart: :heart:

With latest `jscs` and `babel-jscs`, the following code:

``` javascript
var obj = {
    foo () {
    },
};
```

with the following `.jscsrc`:

``` json
{
  "esnext": true,
  "requireSpacesInFunctionExpression": {
    "beforeOpeningRoundBrace": true,
    "beforeOpeningCurlyBrace": true
  }
}
```

gives an error:

```
Missing space before opening round brace at index.js :
     1 |var obj = {
     2 |    foo () {
-----------------^
     3 |    },
     4 |};


1 code style error found.
```

**Comment by hzoo** [comment]
Sorry for the delay - should be an easy fix. I'm pretty sure it's because I forgot to add the changes to that rule (looks like it was done in `requireSpacesInAnonymousFunctionExpression`)

**Comment by hzoo** [comment]
Ok made a fix in jscs and verified it fixes it.

**Comment by jussi-kalliokoski** [comment]
Thank you! :+1:
