### ISSUE TITLE
Jsdoc and destructuring

### ISSUE THREAD

**Issue by blazkovicz** [jscs-dev/babel-jscs#23]
I use jscs 2.1.0 with `{"esnext": true, "jsDoc": {"checkRedundantParams": true}}` in WebStorm for inline linting. Jscs highlights param definitions for destructured params (except first) as redundant:

``` javascript
class ServerResponsePage {
  /**
   * Page to show server response.
   * @constructor
   * @param {string} action - response name.
   * @param {string} result - response result. <--- this description is highlighted as redundant
   */
  constructor({query: {action, result}}) {
    // ...
  }
}
```

**Comment by hzoo** [comment]
Thanks for contributing! - Can you report this to https://github.com/jscs-dev/jscs-jsdoc instead? I think it would go better there.

**Comment by hzoo** [comment]
Closing in favor of doing that
