### ISSUE TITLE
Side-effect unescaping HTML from auto-fix

### ISSUE THREAD

**Issue by indexzero** [jscs-dev/babel-jscs#25]
When running using this jscs config:

**.jscsrc**

``` js
{
  "esnext": true,
  "validateQuoteMarks": {
    "mark": "'",
    "escape": true
  }
}
```

on this code:

``` js
import {Component} from 'react';
export default class AnyCode extends Component {
  render() {
    return (
      <div className="highlight">
        <pre>
          <code className="language-html" data-lang="html">
            <span className="nt">&lt;button</span>
          </code>
        </pre>
      </div>
    )
  }
}
```

Causes the `&lt;` to become `<`. This is a side effect of a bug in `bablyon` in which the `Node` has the correct `rawValue` of `&lt;`, but a **value** of `<`. This `value` property is what the TOKEN gets when used in `babel-jscs` (see: [babel-jscs@2.0.5 code](https://github.com/jscs-dev/babel-jscs/blob/v2.0.5/index.js#L55-L78))

I have not had a chance to try this against the `3.0.0-beta` yet, but I wanted to log this in case anyone else was interested in investigating it further.

**Comment by hzoo** [comment]
JSCS 3.0 doesn't need to use babel-jscs anymore since CST uses babylon underneath, let me know if that works out.
