### ISSUE TITLE
Shorthand methods don't cooperate with space checks

### ISSUE THREAD

**Issue by mgol** [jscs-dev/babel-jscs#4]
The following code:

``` js
var o = {
  f() {},
};
```

with `.jscsrc`:

``` json
{
    "esprima": "./node_modules/babel-jscs",

    "requireSpacesInAnonymousFunctionExpression": {
        "beforeOpeningRoundBrace": true
    }
}
```

errors:

```
Missing space before opening round brace at app/modules/services/selection.js :
     1 |var o = {
     2 |    f() {},
--------------^
     3 |};
     4 |
```

**Comment by mzgol** [comment]
The following code:
```js
var o = {
  f() {},
};
```
with `.jscsrc`:
```json
{
    "esprima": "./node_modules/babel-jscs",

    "requireSpacesInAnonymousFunctionExpression": {
        "beforeOpeningRoundBrace": true
    }
}
```
errors:
```
Missing space before opening round brace at app/modules/services/selection.js :
     1 |var o = {
     2 |    f() {},
--------------^
     3 |};
     4 |
```

**Comment by hzoo** [comment]
Are you on jscs master branch? Also, can you reproduce without `babel-jscs`?

**Comment by mgol** [comment]
It doesn't work for me even with:

``` json
    "jscs": "git://github.com/jscs-dev/node-jscs.git#8de3850aff54e1519bd196a0627ee1cc3b6a96a0",
```

I get errors for both this rule & `validateQuoteMarks`.

**Comment by mgol** [comment]
It works without `babel-jscs` if I set `"esprima": true`, both with JSCS 1.13.1 & from `master`.

**Comment by hzoo** [comment]
I can reproduce with the regular parser + esnext. So an jscs issue (just need to check `node.parent.method === true`) - I'l make a PR later.

**Comment by hzoo** [comment]
Actually @mzgol isn't the error correct anyway?

The issue to me is that `f () {},` (a shorthand method with a space might also error) which I will fix

**Comment by mgol** [comment]
> Actually @mzgol isn't the error correct anyway?

I don't think so; `requireSpacesInAnonymousFunctionExpression` should affect only anonymous expressions. IMO the idea behind this rule is to always separate `function` and the brace, not the function name and the brace.

**Comment by hzoo** [comment]
I guess it's because in the parser these are `FunctionExpression` with `id === null` so in that sense they are anonymous functions because the parent is type `Property` and `parent.method === true`

**Comment by hzoo** [comment]
I guess it depends on whether we think it should skip the rule when encountering a shorthand method (do  we want to add a `requireSpacesInGetter`, `requireSpacesInSetter`, `requireSpacesInShorthandMethod`, `requireSpacesInClassMethod` and same for `disallow`)

@mrjoelkemp

Related is https://github.com/jscs-dev/node-jscs/issues/1066

**Comment by mrjoelkemp** [comment]
In the following code:

```js
var o = {
  f() {},
};
```

`f() {}` is sugar for `f: function() {}`. `f()` is part of the function signature (as you'd define params like `f(foo, bar)`), so it should adhere to the rules.
