### ISSUE TITLE
parseError: undefined on function declaraion

### ISSUE THREAD

**Issue by okonet** [jscs-dev/babel-jscs#6]
For this source file:

```
var a = 1;
function() {} // will fail
function () {} // will fail
```

I'm getting following `parseError`:

```
./node_modules/.bin/jscs ./babel-jscs-sample.js                   2 ↵
parseError: undefined at ./babel-jscs-sample.js :
     1 |var a = 1;
     2 |function() {} // will fail
----------------^
     3 |function () {} // will fail
     4 |


1 code style error found.
```

**Comment by mdevils** [comment]
Hello @okonet, you are getting parse error because your JavaScript code contains syntax error. Run this code in Chrome/Firefox, for instance.
Function expressions cannot be used as function declarations.

**Comment by okonet** [comment]
Yes, I've just realized my example is a faulty one. Sorry for inconvenience.
