### ISSUE TITLE
requireSpacesInFunctionExpression issue

### ISSUE THREAD

**Issue by vesparny** [jscs-dev/babel-jscs#8]
Using:

``` json
"requireSpacesInFunctionExpression": {
    "beforeOpeningRoundBrace": true
  }
```

doesn't seem to work for ES6 classes methods

``` js
// no problem here
function ciao () {
  console.log('ciao');
}

// error here, despite the space
class Ciao {
  ciao () {
    console.log('ciao');
  }
}

```

this is the output from the console
![screen shot 2015-06-25 at 10 15 40](https://cloud.githubusercontent.com/assets/82070/8350200/99d7e15a-1b23-11e5-8bfc-c6905a9f4f77.png)

It works using `esprima-fb`

**Comment by hzoo** [comment]
Thanks for the report - I think it's the same issue as https://github.com/jscs-dev/babel-jscs/issues/4. I'l need to do a fix in upstream (jscs)?

What happens with the regular parser and esnext: true?

I'l try to get a fix in soon if it is an issue with jscs.

**Comment by vesparny** [comment]
Yeah I guess it's a duplicate.
With esprima-fb works.
